//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireBoxingMembershipSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT_PROFILE
    {
        public string CLT_ID { get; set; }
        public string CLT_TYPE { get; set; }
        public string STATUS { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_INITIAL { get; set; }
        public string FULL_NAME { get; set; }
        public System.DateTime MEMBERSHIP_DATE { get; set; }
        public System.DateTime EXPIRATION_DATE { get; set; }
        public string MED_RECORD { get; set; }
        public int BOXING { get; set; }
        public int MUAY_THAI { get; set; }
        public int BASSCON { get; set; }
        public int MMA { get; set; }
        public int FREE_BOXING { get; set; }
        public int FREE_MUAY_THAI { get; set; }
        public int FREE_BASSCON { get; set; }
        public int FREE_MMA { get; set; }
        public decimal BOXING_RATE { get; set; }
        public decimal MUAY_THAI_RATE { get; set; }
        public decimal BASSCON_RATE { get; set; }
        public decimal MMA_RATE { get; set; }
        public string AGE { get; set; }
        public string ADDRESS { get; set; }
        public string CONTACT_NO { get; set; }
        public string GENDER { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> SESSION_EXPIRY { get; set; }
        public Nullable<System.DateTime> FREE_SESSION_EXPIRY { get; set; }
        public string IMAGE_LOC { get; set; }
        public Nullable<int> CORP_GROUP_NAME { get; set; }
        public string TYPE { get; set; }
        public Nullable<System.DateTime> UNLIMITED_EXPIRY { get; set; }
        public string UNLIMITED_SRVC { get; set; }
    }
}
