//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireBoxingMembershipSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpireBoxingEntities : DbContext
    {
        public EmpireBoxingEntities()
            : base("name=EmpireBoxingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CLIENT_PROFILE> CLIENT_PROFILE { get; set; }
        public virtual DbSet<GROUP_CORPORATE_MEMBERS> GROUP_CORPORATE_MEMBERS { get; set; }
        public virtual DbSet<GROUP_CORPORATE_PROFILE> GROUP_CORPORATE_PROFILE { get; set; }
        public virtual DbSet<PAYMENT_HISTORY> PAYMENT_HISTORY { get; set; }
        public virtual DbSet<SESSION_RATE> SESSION_RATE { get; set; }
        public virtual DbSet<SESSION_USED_HISTORY> SESSION_USED_HISTORY { get; set; }
        public virtual DbSet<TIME_RECORD> TIME_RECORD { get; set; }
        public virtual DbSet<USER_ACCOUNT> USER_ACCOUNT { get; set; }
    }
}
