//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireBoxingMembershipSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT_HISTORY
    {
        public int ID { get; set; }
        public string CLT_ID { get; set; }
        public string METHOD { get; set; }
        public decimal AMOUNT { get; set; }
        public string SESSION_CODE { get; set; }
        public System.DateTime CRT_DATE { get; set; }
        public string CRT_BY { get; set; }
    }
}
