//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireBoxingMembershipSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class SESSION_USED_HISTORY
    {
        public string CLT_ID { get; set; }
        public string SRVC_CODE { get; set; }
        public Nullable<System.DateTime> CRT_DATE { get; set; }
        public int SESS_HIST_ID { get; set; }
        public string CRT_BY { get; set; }
    }
}
