//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireBoxingMembershipSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_RECORD
    {
        public string CLT_CODE { get; set; }
        public Nullable<System.DateTime> TIME_IN { get; set; }
        public Nullable<System.DateTime> TIME_OUT { get; set; }
        public string SRVC_CODE { get; set; }
        public int TR_ID { get; set; }
        public string CRT_BY { get; set; }
    }
}
