//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmpireBoxingMembershipSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ACCOUNT
    {
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
        public string CRT_BY { get; set; }
        public Nullable<System.DateTime> CRT_DATE { get; set; }
        public string ACCESS_LVL { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string MIDDLE_INITIAL { get; set; }
    }
}
